name: Continuous Integration

on: [push]

env:
  CI: true
  FORCE_COLOR: '1' # https://github.com/chalk/chalk/issues/203

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: yarn install, build, and test
        run: yarn lint
